image: owend/node:6.2.2
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'droneCI'
    channel: '#testing'
    on_started: false
    on_success: true
    on_failure: true
branches:
  - master
deploy:
  bash:
    script:
      # custom docker images
      # require you to bootstrap the ssh-agent
      - eval `ssh-agent -s`
      - ssh-add ~/.ssh/id_rsa
      - export AWS_ACCESS_KEY_ID=$AWS_KEY
      - export AWS_SECRET_ACCESS_KEY=$AWS_SEC
      # - ssh -T git@github.com
      - cd .drone
      - ./deploy.sh
    when:
      branch: master
